### ISSUE TITLE
Exported file imported immediately

### ISSUE THREAD

**Issue by fzsozso** [uniface/Development-Tooling#7]
When sync exports a file then imports immediately the exported resource file.
This is maybe because SOURCE_DIR  has an extra "\"  in FILEPATH and VC_STATUS has two lines for one resource item. For example: FILEPATH are c:\txt\aa.cmx and c:\txt\\a.cmx  where SOURCE_DIR is c:\txt

**Comment by uf-dakerman** [comment]
Your description is a little unclear, so i'm not 100% sure what issue you are experiencing.
In your comment . I don't know what you mean by  SOURCE_DIR has an extra "" in FILEPATH , and if you are saying that VC_STATUS has two records for one component, then you have a data corruption issue of some sort and need to delete a record. You mention aa.cmx and a.cmx - these would be two different components, so I would expect two different VC_STATUS records.

I just tried modifying a form and synchronizing - it only exported and the form wasn't re-imported.  
The tool generally works by exporting changes in the repository, then importing new files from the filesystem (using the VC_STATUS table to record last export and import times). If VALIDATE_IMPORT_STAMP is set to 1 your .asn it will compare export file timestamps with the Uniface repository before importing, otherwise it will just use the filesystem time (faster, but risk of overwriting with an old version if you change the export file). 

It may export and re-import on first use (I don't have time to try it right now), but that shouldn't cause a problem in a sandbox environment.

As you have the source code, I suggest you run the sync tool with a debugger to identify the cause of your problem, as I can't reproduce it from the description you gave (perhaps you can elaborate)?

**Comment by fzsozso** [comment]
it looks something hide some slash character I typed. Actually I deleted everything, and started from the beginning, and now it works well. I don't know what was the problem at first attempt. Thanks!
